# Generated by Django 3.2.8 on 2022-01-05 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('roll_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('department', models.ManyToManyField(to='firstapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher1',
            fields=[
                ('emp_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.department')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
