# Generated by Django 3.2.8 on 2022-01-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20220105_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_stud', to='firstapp.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ManyToManyField(related_name='department_teach', to='firstapp.Department'),
        ),
    ]
